#pragma once
#ifndef COMMON_H
#define COMMON_H

#define CACHE_LINE_SIZE (64)

#define THREAD_PRODUCER_SLEEP_TIME_SECONDS 4s
#define THREAD_CONSUMER_SLEEP_TIME_SECONDS 1s
#define THREAD_CONSUMER_RETRY_SLEEP_DELAY_SECONDS 0.3s
#define CONSUMER_THREADS_START_TIMEOUT 1s

#define STOP_CONSUMER_VALUE (-1)

#define MAX_PRODUCE_ATTEMPTS (5)

#endif